-- Criação da tabela CURSOS
CREATE TABLE USR_GESTAO_ACAD.CURSOS (
    CURSO_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO CLOB,
    DURACAO NUMBER CHECK (DURACAO > 0),
    CONSTRAINT PK_CURSOS PRIMARY KEY (CURSO_ID),
    CONSTRAINT UNQ_CURSOS_NOME UNIQUE (NOME)
);

-- Criação da tabela PROFESSORES
CREATE TABLE USR_GESTAO_ACAD.PROFESSORES (
    PROFESSOR_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DEPARTAMENTO VARCHAR2(100),
    CONSTRAINT PK_PROFESSORES PRIMARY KEY (PROFESSOR_ID)
);

-- Criação da tabela DISCIPLINAS
CREATE TABLE USR_GESTAO_ACAD.DISCIPLINAS (
    DISCIPLINA_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CURSO_ID NUMBER,
    PROFESSOR_ID NUMBER,
    CONSTRAINT PK_DISCIPLINAS PRIMARY KEY (DISCIPLINA_ID),
    CONSTRAINT FK_DISCIPLINAS_CURSOS FOREIGN KEY (CURSO_ID) REFERENCES USR_GESTAO_ACAD.CURSOS (CURSO_ID),
    CONSTRAINT FK_DISCIPLINAS_PROFESSORES FOREIGN KEY (PROFESSOR_ID) REFERENCES USR_GESTAO_ACAD.PROFESSORES (PROFESSOR_ID)
);

-- Criação da tabela ESTUDANTES sem a restrição CHECK para DATA_NASCIMENTO
CREATE TABLE USR_GESTAO_ACAD.ESTUDANTES (
    ESTUDANTE_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    MATRICULA VARCHAR2(20) NOT NULL UNIQUE,
    CURSO_ID NUMBER,
    CONSTRAINT PK_ESTUDANTES PRIMARY KEY (ESTUDANTE_ID),
    CONSTRAINT FK_ESTUDANTES_CURSOS FOREIGN KEY (CURSO_ID) REFERENCES USR_GESTAO_ACAD.CURSOS (CURSO_ID)
);

-- Criação da trigger para validar a restrição de DATA_NASCIMENTO
CREATE OR REPLACE TRIGGER TRG_VALIDATE_DATA_NASCIMENTO
BEFORE INSERT OR UPDATE ON USR_GESTAO_ACAD.ESTUDANTES
FOR EACH ROW
BEGIN
    IF :NEW.DATA_NASCIMENTO >= SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20001, 'DATA_NASCIMENTO deve ser menor que a data atual.');
    END IF;
END;
/

-- Criação da tabela MATRICULAS sem a restrição CHECK para DATA_MATRICULA
CREATE TABLE USR_GESTAO_ACAD.MATRICULAS (
    MATRICULA_ID NUMBER NOT NULL,
    ESTUDANTE_ID NUMBER NOT NULL,
    DISCIPLINA_ID NUMBER NOT NULL,
    DATA_MATRICULA DATE DEFAULT SYSDATE,
    CONSTRAINT PK_MATRICULAS PRIMARY KEY (MATRICULA_ID),
    CONSTRAINT FK_MATRICULAS_ESTUDANTES FOREIGN KEY (ESTUDANTE_ID) REFERENCES USR_GESTAO_ACAD.ESTUDANTES (ESTUDANTE_ID),
    CONSTRAINT FK_MATRICULAS_DISCIPLINAS FOREIGN KEY (DISCIPLINA_ID) REFERENCES USR_GESTAO_ACAD.DISCIPLINAS (DISCIPLINA_ID)
);

-- Trigger para validar que DATA_MATRICULA não pode ser maior que SYSDATE
CREATE OR REPLACE TRIGGER TRG_VALIDATE_DATA_MATRICULA
BEFORE INSERT OR UPDATE ON USR_GESTAO_ACAD.MATRICULAS
FOR EACH ROW
BEGIN
    IF :NEW.DATA_MATRICULA > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20002, 'DATA_MATRICULA não pode ser maior que a data atual.');
    END IF;
END;
/